package mcpserver

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/sharedcode/joltrin/v5/tools/blocklog"
	"github.com/sharedcode/joltrin/v5/tools/runbookstore"
	"github.com/sharedcode/joltrin/v5/verify"
)

// This file is the optional memory: the server remembers which steps were
// blocked in earlier runs and tells the next agent, in two places. The MCP
// server instructions reach any MCP client when a session starts. A markdown
// file can be added to a CLAUDE.md or AGENTS.md for agents that read one. Both
// carry the same short lines. It is off unless WithMemory is used, and it is
// advisory: the barrier checks every call exactly as before.

const (
	maxLessonsPerWorkflow = 5
	maxLessons            = 10
)

type config struct {
	log         *blocklog.Log
	lessonsPath string
}

// Option configures New.
type Option func(*config)

// WithMemory makes the server record each block, once per run, in log, and
// tell later agents about them. The lessons appear in the server instructions
// returned when a client connects, and, if lessonsPath is not empty, in a
// markdown file that is rewritten whenever a new block is recorded. A failure
// to write either never changes what the barrier does.
func WithMemory(log *blocklog.Log, lessonsPath string) Option {
	return func(c *config) {
		c.log = log
		c.lessonsPath = lessonsPath
	}
}

// workflowVersion fingerprints a runbook's steps and safety rules, so recorded
// blocks stop applying once the runbook changes.
func workflowVersion(wf *verify.Workflow) string {
	b, _ := json.Marshal(describeWorkflow(wf))
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:8])
}

// shortID stands in for the caller-supplied trace id in the log. The id is
// free text from the client, so only a short hash is kept: enough to tell runs
// apart, and it keeps each entry a fixed size.
func shortID(id string) string {
	sum := sha256.Sum256([]byte(id))
	return hex.EncodeToString(sum[:6])
}

// recordBlock stores a block in the log and refreshes the lessons file when it
// was new. Errors are dropped on purpose: memory must never affect the barrier.
func (c *config) recordBlock(store *runbookstore.Store, workflow, traceID, step string, wf *verify.Workflow, v *verify.Violation) {
	if c.log == nil {
		return
	}
	added, _ := c.log.Record(blocklog.Entry{
		Workflow:      workflow,
		Version:       workflowVersion(wf),
		TraceID:       shortID(traceID),
		Step:          verify.StepID(step),
		BlockedBy:     v.Rule,
		MissingState:  v.MissingState,
		EstablishedBy: wf.StepsThatEstablish(v.MissingState),
	})
	if added {
		c.writeLessons(store)
	}
}

func (c *config) writeLessons(store *runbookstore.Store) {
	if c.log == nil || c.lessonsPath == "" {
		return
	}
	body := lessonsFile(lessonLines(store, c.log))
	if err := os.MkdirAll(filepath.Dir(c.lessonsPath), 0o755); err != nil {
		return
	}
	tmp := c.lessonsPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return
	}
	_ = os.Rename(tmp, c.lessonsPath)
}

// instructions is the text sent to a client when it connects, or "" when
// there is nothing to say yet.
func instructions(store *runbookstore.Store, log *blocklog.Log) string {
	lines := lessonLines(store, log)
	if len(lines) == 0 {
		return ""
	}
	return "Lessons recorded by this server from earlier runs. They are advisory: the barrier still checks every call, and a blocked step returns the missing state and the steps that would establish it.\n" +
		strings.Join(lines, "\n")
}

func lessonsFile(lines []string) string {
	head := "# Joltrin lessons\n\nGenerated by sop-mcp-server from blocks in earlier runs. Do not edit it, it is rewritten when a new block is recorded. Advisory only: the barrier still checks every call.\n\n"
	if len(lines) == 0 {
		return head + "No blocks recorded yet.\n"
	}
	return head + strings.Join(lines, "\n") + "\n"
}

// lessonLines turns the recorded blocks into short plain lines, a few per
// runbook and a few overall, most frequent first.
func lessonLines(store *runbookstore.Store, log *blocklog.Log) []string {
	var lines []string
	for _, name := range store.WorkflowNames() {
		wf, ok := store.Workflow(name)
		if !ok {
			continue
		}
		sums := log.Summaries(name, workflowVersion(wf))
		if len(sums) > maxLessonsPerWorkflow {
			sums = sums[:maxLessonsPerWorkflow]
		}
		for _, s := range sums {
			lines = append(lines, lessonLine(name, wf, s))
		}
	}
	if len(lines) > maxLessons {
		lines = lines[:maxLessons]
	}
	return lines
}

func lessonLine(workflow string, wf *verify.Workflow, s blocklog.Summary) string {
	runs := fmt.Sprintf("%d runs", s.Runs)
	if s.Runs == 1 {
		runs = "1 run"
	}
	rule := ""
	if s.BlockedBy != "precondition" {
		rule = fmt.Sprintf(" (rule: %s)", s.BlockedBy)
	}
	if order := fixOrder(wf, s.MissingState); len(order) > 0 {
		return fmt.Sprintf("- %s: before %s, run %s. It was blocked in %s for missing state %s%s.",
			workflow, s.Step, joinSteps(order, ", then "), runs, s.MissingState, rule)
	}
	if len(s.EstablishedBy) > 0 {
		return fmt.Sprintf("- %s: %s was blocked in %s for missing state %s%s. Steps that establish it: %s.",
			workflow, s.Step, runs, s.MissingState, rule, joinSteps(s.EstablishedBy, ", "))
	}
	return fmt.Sprintf("- %s: %s was blocked in %s for missing state %s%s. No step in this runbook establishes it.",
		workflow, s.Step, runs, s.MissingState, rule)
}

func joinSteps(ids []verify.StepID, sep string) string {
	parts := make([]string, len(ids))
	for i, id := range ids {
		parts[i] = string(id)
	}
	return strings.Join(parts, sep)
}

// fixOrder returns the steps to run, in order, to establish state, following
// each step's own requirements back to the start. It returns nil when the path
// is not clear: a state that no step, or more than one step, establishes, or a
// cycle.
func fixOrder(wf *verify.Workflow, state verify.State) []verify.StepID {
	est := wf.StepsThatEstablish(state)
	if len(est) != 1 {
		return nil
	}
	var order []verify.StepID
	visiting := map[verify.StepID]bool{}
	done := map[verify.StepID]bool{}
	var visit func(id verify.StepID) bool
	visit = func(id verify.StepID) bool {
		if done[id] {
			return true
		}
		if visiting[id] {
			return false
		}
		visiting[id] = true
		for _, req := range wf.Steps[id].Requires {
			e := wf.StepsThatEstablish(req)
			if len(e) != 1 || !visit(e[0]) {
				return false
			}
		}
		visiting[id] = false
		done[id] = true
		order = append(order, id)
		return true
	}
	if !visit(est[0]) {
		return nil
	}
	return order
}
